import { Injectable, inject, OnDestroy } from '@angular/core';
import {
  Firestore,
  collection,
  doc,
  onSnapshot,
  setDoc,
  DocumentReference,
} from '@angular/fire/firestore';
import { UserInterface } from '../interfaces/user.interface';

@Injectable({
  providedIn: 'root',
})
export class UsersService implements OnDestroy {
  firestore: Firestore = inject(Firestore);
  users: UserInterface[] = [];
  unsubscribeUser;

  constructor() {
    this.unsubscribeUser = this.subUsersList();
  }

  ngOnDestroy(): void {
    // if (this.unsubscribeUser) {
    //   this.unsubscribeUser();
    // }
  }

  getUsersRef() {
    return collection(this.firestore, 'users');
  }

  subUsersList() {
    return onSnapshot( this.getUsersRef(),(snapshot) => {
        this.users = [];
        snapshot.forEach((element) => {
          const user = element.data();
          // this.users.push( this.usersContactsService.setObjectData(element.id, user));
        });
      },
      (error) => {
        console.error('Firestore Error', error.message);
      }
    );
  }

    /**
   * Adds a new user to the Firestore database.
   * The user will be given a random color generated by UsersContactsService.
   * @param uid The unique identifier for the user
   * @param user The user data to be added
   * @returns A promise that resolves with the document reference of the newly added user
   */
  async addUser( uid: string, user: UserInterface): Promise<void | DocumentReference> {
    try {
      const userRef = doc(this.getUsersRef(), uid);
      await setDoc(userRef, user);
      return userRef;
    } catch (err) {
      console.error(err);
    }
  }
}
